### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [1]:
# np.array
import numpy as np

a = np.array([1,2,3]) # This is a vector
print(a)

[1 2 3]


In [2]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]]) # This is a matrix
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # This is a tensor
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
# To check number of dimensions

print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [3]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [4]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [5]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [9]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
# np.random
np.random.random((3,4))

array([[0.68119079, 0.41904315, 0.14139046, 0.06638954],
       [0.85820572, 0.12569789, 0.42445277, 0.15294268],
       [0.19375286, 0.34645361, 0.49587714, 0.22163105]])

In [12]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [13]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [14]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# ndim
a3.ndim

In [15]:
# shape
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [16]:
# size
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [17]:
# itemsize
a3.itemsize

8

In [18]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


### Changing Datatype

In [19]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [20]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [22]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [23]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions
- https://numpy.org/doc/stable/reference/routines.math.html
- https://numpy.org/doc/stable/reference/ufuncs.html

In [24]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[94., 46., 46.],
       [80., 57., 32.],
       [42., 63., 87.]])

In [27]:
# max/min/sum/prod
# axis : 0 -> col and 1 -> row
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1,axis=0))

94.0
32.0
547.0
[315840. 165186. 128064.]


In [28]:
# mean/median/std/var
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1,axis=1))

60.77777777777778
57.0
20.541436592506145
[512.         384.22222222 338.        ]


In [29]:
# trigonomoetric functions
np.sin(a1)

array([[-0.24525199,  0.90178835,  0.90178835],
       [-0.99388865,  0.43616476,  0.55142668],
       [-0.91652155,  0.1673557 , -0.82181784]])

In [30]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [33]:
# log and exponents
print(np.exp(a1))
print()
print(np.log(a1))

[[6.66317622e+40 9.49611942e+19 9.49611942e+19]
 [5.54062238e+34 5.68572000e+24 7.89629602e+13]
 [1.73927494e+18 2.29378316e+27 6.07603023e+37]]

[[4.54329478 3.8286414  3.8286414 ]
 [4.38202663 4.04305127 3.4657359 ]
 [3.73766962 4.14313473 4.46590812]]


In [34]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[69.,  9.,  8.],
       [36., 27., 50.]])

### Indexing and Slicing

In [35]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [36]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a1[-1]

9

In [40]:
a1[0]

0

In [41]:
a1[2] + a1[6]

8

In [42]:
a1[-3:-1]

array([7, 8])

In [43]:
a1[1:7]

array([1, 2, 3, 4, 5, 6])

In [37]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
print(a2[1][1])
print(a2[2][3])
print(a2[2,3])
print(a2[1:7])
print(a2[-3:-1])
print(a2[::2,::3])

5
11
11
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 0  3]
 [ 8 11]]


In [38]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [56]:
print(a3[0,1,1])
print(a3[-1,-2,-1])
print(a3[-1])

3
5
[[4 5]
 [6 7]]
[]


In [59]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [60]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [61]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [62]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [63]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [64]:
a2

for i in np.nditer(a2):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [66]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [67]:
# Transpose
np.transpose(a2) #Method 1
a2.T #Method 2

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [68]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [72]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

print(a4)
print()
print(a5)
print()

# horizontal stacking
print(np.hstack((a4,a5)))

print()

# Vertical stacking
print(np.vstack((a4,a5)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


### Splitting

In [78]:
# horizontal splitting
print(np.hsplit(a4,4))

print()

# vertical splitting
print(np.vsplit(a4,3))

[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
