### np.sort

- Return a sorted copy of an array.

- https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [ ]:
# code
import numpy as np
a = np.random.randint(1,100,15)
print("a:")
print(a)

print()

b = np.random.randint(1,100,24).reshape(6,4)
print("b:")
print(b)

a:
[24 66 80 34 32  3 63 34 64 78 30 56 83 94 23]

b:
[[30  3 65 54]
 [48 80 17 82]
 [67 15 26 90]
 [87 32 45 96]
 [88 70  7  7]
 [25  9 97 18]]


In [ ]:
np.sort(a) #ascending

array([ 4,  9, 11, 11, 28, 29, 31, 32, 38, 50, 53, 60, 62, 79, 82])

In [ ]:
np.sort(a)[::-1] #descending

array([82, 79, 62, 60, 53, 50, 38, 32, 31, 29, 28, 11, 11,  9,  4])

In [ ]:
# rows wise sorting
np.sort(b)

array([[19, 28, 67, 93],
       [ 3,  6, 23, 60],
       [39, 41, 70, 98],
       [ 5, 31, 96, 99],
       [15, 20, 21, 57],
       [10, 14, 47, 91]])

In [ ]:
# column wise sorting
np.sort(b,axis=0)   # if axis = 1 (row wise) , axis = 0 (column wise)

array([[ 3, 21,  6, 10],
       [ 5, 23, 14, 19],
       [15, 28, 20, 31],
       [41, 70, 93, 39],
       [47, 91, 98, 57],
       [67, 96, 99, 60]])

### np.append

- The numpy.append() appends values along the mentioned axis at the end of the array

- https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [ ]:
# code
np.append(a,200)

array([ 38,  50,  11,  28,   4,  62,  60,  82,  29,   9,  79,  53,  11,
        31,  32, 200])

In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[67., 28., 93., 19.,  1.],
       [ 3., 23.,  6., 60.,  1.],
       [41., 70., 98., 39.,  1.],
       [ 5., 96., 99., 31.,  1.],
       [15., 21., 20., 57.,  1.],
       [47., 91., 14., 10.,  1.]])

In [ ]:
np.append(b,np.random.random((b.shape[0],1)),axis=1) #column wise

array([[67.        , 28.        , 93.        , 19.        ,  0.68145424],
       [ 3.        , 23.        ,  6.        , 60.        ,  0.42799827],
       [41.        , 70.        , 98.        , 39.        ,  0.10536152],
       [ 5.        , 96.        , 99.        , 31.        ,  0.69259678],
       [15.        , 21.        , 20.        , 57.        ,  0.3684835 ],
       [47.        , 91.        , 14.        , 10.        ,  0.98424108]])

### np.concatenate

- numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

- https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print()
print(d)

[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0) # row wise

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

- With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

- https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [ ]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

- With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

- https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [ ]:
# code
a
a.shape

(15,)

In [ ]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [ ]:
np.expand_dims(a,axis=1)

array([[38],
       [50],
       [11],
       [28],
       [ 4],
       [62],
       [60],
       [82],
       [29],
       [ 9],
       [79],
       [53],
       [11],
       [31],
       [32]])

### np.where

- The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

- https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 5,  6,  7, 10, 11]),)

In [ ]:
# replace all values > 50 with 0
# np.where(conition,true,false)
np.where(a>50,0,a)

array([38, 50, 11, 28,  4,  0,  0,  0, 29,  9,  0,  0, 11, 31, 32])

In [ ]:
np.where(a%2 == 0 , 0 , a)

array([ 0,  0, 11,  0,  0,  0,  0,  0, 29,  9, 79, 53, 11, 31,  0])

### np.argmax

- The numpy.argmax() function returns indices of the max element of the array in a particular axis.

- https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [ ]:
np.argmax(a)

7

In [ ]:
np.argmax(b,axis=0)

array([0, 3, 3, 1])

In [ ]:
np.argmax(b,axis=1)

array([2, 3, 2, 2, 3, 1])

In [ ]:
# np.argmin
np.argmin(a)

4

### np.cumsum

- numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

- https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [ ]:
np.cumsum(a)

array([ 38,  88,  99, 127, 131, 193, 253, 335, 364, 373, 452, 505, 516,
       547, 579])

In [ ]:
np.cumsum(b)

array([  67,   95,  188,  207,  210,  233,  239,  299,  340,  410,  508,
        547,  552,  648,  747,  778,  793,  814,  834,  891,  938, 1029,
       1043, 1053])

In [ ]:
np.cumsum(b,axis=1)

array([[ 67,  95, 188, 207],
       [  3,  26,  32,  92],
       [ 41, 111, 209, 248],
       [  5, 101, 200, 231],
       [ 15,  36,  56, 113],
       [ 47, 138, 152, 162]])

In [ ]:
# np.cumprod
np.cumprod(a)

array([                  38,                 1900,                20900,
                     585200,              2340800,            145129600,
                 8707776000,         714037632000,       20707091328000,
            186363821952000,    14722741934208000,   780305322513024000,
        8583358547643264000,  7829697945007461376, -7704082791694958592])

### np.percentile

- numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

- https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [ ]:
np.percentile(a,50)

32.0

In [ ]:
np.median(a)

32.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
np.histogram(a,bins=[0,50,100])

(array([9, 6]), array([  0,  50, 100]))

### np.corrcoef

- Return Pearson product-moment correlation coefficients.

- https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

- With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

- https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [ ]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([50, 60])

### np.flip

- The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

- https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [ ]:
np.flip(a)

array([23, 94, 83, 56, 30, 78, 64, 34, 63,  3, 32, 34, 80, 66, 24])

In [ ]:
np.flip(b,axis=1)

array([[54, 65,  3, 30],
       [82, 17, 80, 48],
       [90, 26, 15, 67],
       [96, 45, 32, 87],
       [ 7,  7, 70, 88],
       [18, 97,  9, 25]])

### np.put

- The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

- https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [ ]:
np.put(a,[0,1],[110,530])

In [ ]:
a

array([110, 530,  80,  34,  32,   3,  63,  34,  64,  78,  30,  56,  83,
        94,  23])

### np.delete

- The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

- https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [ ]:
np.delete(a,[0,2,4])

array([530,  34,   3,  63,  34,  64,  78,  30,  56,  83,  94,  23])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

In [ ]:
np.intersect1d(m,n)

In [ ]:
np.setdiff1d(n,m)

In [ ]:
np.setxor1d(m,n)

In [ ]:
m[np.in1d(m,1)]

### np.clip

- numpy.clip() function is used to Clip (limit) the values in an array.

- https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [ ]:
np.clip(a,a_min=25,a_max=75)